package com.rcorrent.personsignup.server.validation.exception;

import javax.validation.ConstraintViolation;
import javax.validation.Validator;
import java.util.Map;

public class IndexedLogicError extends LogicError {

    private final String index;

    /**
     * Constructor with {@code index}, {@code field} and {@code message} initialization.
     *
     * @param index   in which the entity is located
     * @param field   that has been validated in the entity
     * @param message indicating the result of the validation
     */
    public IndexedLogicError(final String index, final String field, final String message) {
        super(field, message, null/*value*/, null/*params*/);

        this.index = index;
    }

    /**
     * Constructor with default {@link #IndexedLogicError(String, String, String)} initialization plus {@code messageTemplate},
     * {@code value} and {@code param} initialization.
     *
     * @param index           in which the entity is located
     * @param field           that has been validated in the entity
     * @param messageTemplate to perform internationalization
     * @param message         that already was internationalized
     * @param value           as validation value
     * @param params          as message arguments
     */
    public IndexedLogicError(final String index,
                             final String field,
                             final String messageTemplate,
                             final String message,
                             final String value,
                             final Map<String, Object> params) {
        super(field, messageTemplate, message, value, params);

        this.index = index;
    }

    /**
     * Constructor with {@code index} and {@code constraintViolation} initialization.
     *
     * @param index               in which the entity is located
     * @param constraintViolation generated by bean validation
     * @see ConstraintViolation
     * @see Validator#validate(Object, Class...)
     */
    public IndexedLogicError(final String index, final ConstraintViolation<?> constraintViolation) {
        super(
                constraintViolation.getPropertyPath() != null ? constraintViolation.getPropertyPath().toString() : null,
                constraintViolation.getMessageTemplate(),
                constraintViolation.getMessage(),
                constraintViolation.getInvalidValue() != null ? constraintViolation.getInvalidValue().toString() : null,
                constraintViolation.getConstraintDescriptor() != null ? constraintViolation.getConstraintDescriptor().getAttributes() : null
        );

        this.index = index;
    }

    /**
     * Gets the error index.
     *
     * @return the error index
     */
    public String getIndex() {
        return index;
    }

}
